# Custom Language File for Launcher Customizer

[ejs.app]
title = "SAO Chronicles Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/remyShift/SAO_Chronicles_Launcher"
mediaTiktokURL = "https://www.tiktok.com/@saochroniclesfr"
mediaDiscordURL = "https://discord.gg/69yYyXUJ8Z"
mediaInstagramURL = "https://www.instagram.com/sao_chronicles?igsh=cmYyN3Z0NDJyeTNx"

[ejs.settings]
sourceGithubLink = "https://github.com/remyShift/SAO_Chronicles_Launcher"
supportLink = "https://github.com/remyShift/SAO_Chronicles_Launcher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO SAO CHRONICLES"
welcomeDescription = "Our mission is to recreate the universe imagined by author Kazuto Nakazawa in his fantasy series, SAO Chronicles.  Through the collaborative effort of thousands of community members, we have sought to create SAO Chronicles as accurately and precisely as possible within Minecraft.  The world we are creating is yours to explore.  Journey from the first floor to the final floor in the Aincrad."
welcomeDescCTA = "You are just a few clicks away from SAO Chronicles."
